apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-deploy-app
  labels:
    app: ds-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-app
  template:
    metadata:
      labels:
        app: ds-app
    spec:
      containers:
      - name: web-app
        image: dscharan2001/ds-project
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8235
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ds-deploy-svc
  labels:
    app: ds-app
spec:
  type: LoadBalancer
  selector:
    app: ds-app
  ports:
  - name: http
    port: 80
    targetPort: 8235
